project_name: cxa

before:
  hooks:
    - go mod tidy

builds:
  - id: cxa
    main: ./cmd/cxa
    binary: cxa
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: cxa
    repository:
      owner: delhombre
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/delhombre/codex-account-switcher
    description: Fast, beautiful CLI to manage multiple Codex CLI accounts
    license: MIT
    install: |
      bin.install "cxa"
    test: |
      system "#{bin}/cxa", "version"
